name: Build Profiles

on:
  push:
    paths:
      - "**/build-profiles2.yml"
      - "**.fsh"
      - "**/sushi-config.yaml"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-profiles:
    uses: gematik/fhir-scripts/.github/workflows/build-profiles.yml@feature/github-workflows
