name: Process Requirements

on:
  push:
    paths:
      - "**/process-requirements.yml"
      - "**.md"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-profiles:
    name: Process Requirements
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install fhirscripts
        run: pipx install -f git+https://github.com/gematik/fhir-scripts.git

      - name: Install igtools
        run: fhirscripts install --igtools

      - name: Process requirements
        run: fhirscripts build defs --only-req

      - name: Push changes
        uses: ./actions/push-changes
