name: Process Requirements

on:
  push:
    paths:
      - "**/process-requirements2.yml"
      - "**.md"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-profiles:
    uses: gematik/fhir-scripts/.github/workflows/process-requirements.yml@feature/github-workflows
